### ISSUE TITLE
Consider using py-solc

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#1036]
It's been brought up for discussion that maybe we should use py-solc, instead of our own wrapper. Let's discuss this here.

https://github.com/ethereum/py-solc

https://github.com/trailofbits/manticore/issues/110#issuecomment-411063588

**Comment by mossberg** [comment]
So it seems py-solc still requires an out of band installation of the solc binary.

**Comment by defunctio** [comment]
They do provide this though;
```
>>> from solc import install_solc
>>> install_solc('v0.4.24')
```
with support for both osx/linux

**Comment by ESultanik** [comment]
`py-solc` has a couple issues related to its `install_solc` function:
1. Its support for installation of new versions of `solc` lags behind. Currently, the latest version it supports is v0.4.25.
2. On macOS, `py-solc` installs `solc` from source. This is a problem because `solc` versions 0.4.* no longer build on macOS from source, and [the developers have decided not to fix that issue](https://github.com/ethereum/solidity/issues/5414).

Another option—which would regrettably add a dependency on `npm`—would be to dynamically install the Emscripten-generated `solc-js` version specific to the code being analyzed. This can be done locally per Manticore run without requiring a globally installed `solc` binary. That's what Truffle does. Chances are if someone is running Manticore, they already have Truffle (and thereby `npm` and `solc-js`) installed.

**Comment by ESultanik** [comment]
Another option would be to make Manticore Truffle-aware. See Issue #768. The idea would be for Manticore to auto-detect whether a project it is analyzing is a Truffle project. If so, run `truffle compile` and then read the compiled contracts directly from Truffle. That would remove the dependency on `solc` completely for Truffle projects (of which the vast majority are nowadays).

**Comment by ehennenfent** [comment]
#1406
