### ISSUE TITLE
submit pr to EthereumAnalysisBenchmarks adding a little disclaimer section about manticore's philosophy and design

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#1099]
based on a call we had with that team today :) 

we should submit a pr describing manticore as a kind of disclaimer, because it is not necessarily meant for the tasks the benchmarking table shows. we just need to write a few sentences communicating

- manticore is not really intended for lightweight detection of certain kinds of vulnerabilities
- it was designed for arbitrary discovery of real possible contract states, using a transactional approach
- every state should be reproducible, no false positives in the sense that no infeasible states are generated
- this is more useful for contract verification part of the secure development process, rather than lightweight developer security feedback

https://github.com/EthereumAnalysisBenchmarks/ethereumanalysisbenchmarks.github.io

**Comment by dguido** [comment]
> this is more useful for contract verification part of the secure development process, rather than lightweight developer security feedback

although Manticore _does_ include _some_ out of the box security analyses.

**Comment by mossberg** [comment]
good point. so maybe this:

- in addition to being useful for lightweight security feedback for developers, this is also very useful for the contract verification phase of the secure development process

**Comment by rocky** [comment]
I'm thinking where this text would go is in index.html as another section

 ```<h2 class="mt-5 mb-3">The Tools</h2>```

**Comment by rocky** [comment]
Since time is short for me I have just updated https://ethereumanalysisbenchmarks.github.io/ to include the text given at the top of this issue. Please feel free to correct that and put in a PR. 

I have also updated the Suhabe benchmark suite with results from Oyente. For that I used what I had in @55c1ed but I see there is now a new release out, so I will rerun this later with 0.2.1.1. 

I  will be leaving on Sunday for Berlin and we are having a Diligence huddle the beginning of the week, so I may have limited time and access.

**Comment by dguido** [comment]
Thanks, we'll submit a PR to adjust the language soon. In between writing this thread and today, we made a release that includes a full suite of Ethereum detectors so we'll definitely reframe it appropriately.

**Comment by mossberg** [comment]
done: https://github.com/SmartContractSecurity/smartcontractsecurity.github.io/pull/6
