### ISSUE TITLE
Questions on options

### ISSUE THREAD

**Issue by SunBeomSo** [trailofbits/manticore#1582]
I have four questions about Manticore's options below:
```
  --core.procs CORE.PROCS
                        Number of parallel processes to spawn (default: 10)
  --core.mprocessing CORE.MPROCESSING
                        single: No multiprocessing at all. Single process.
                        threading: use threads multiprocessing: use forked
                        processes (default: MProcessingType.multiprocessing)
```

**Question 1**
What does the``process`` mean in the above explanations? Is ``1 process = 1 invocation of Z3`` for solving queries (e.g., path constraints or checking safety conditions)?

**Question 2**
If I provide an option ``--core.mprocessing single``, then is it equivalent to the option ``--core.procs 1``?

**Question 3**
Why is the default value of ``--core.procs`` set to  10? Is it because 10 is the most recommended value? My machine has only 8 cpus available.

**Question 4**
Regarding `` --core.mprocessing`` option, why are the two arguments (``threading`` and ``processes``)  are differentiated?

**Comment by ehennenfent** [comment]
1. This is not how many total processes Manticore is allowed to create, but rather how many [Workers](https://github.com/trailofbits/manticore/blob/master/manticore/core/worker.py) will be created to explore states. While workers can invoke Z3 independently, they won't be exploring states (executing instructions) while waiting on output from Z3, so this shouldn't cause a CPU bottleneck. 

4. We use the worker model so that we can explore states in parallel. Workers can function in three different ways. `WorkerProcess` uses `multiprocessing.Process` to explore states, whereas `WorkerThread` uses `threading.Thread`. `WorkerSingle` has the same API as the other two, but doesn't actually create any new processes or threads, instead opting to do state exploration in the main process.

3. To my knowledge, there's no particular reason for this. We should probably replace it with `multiprocessing.cpu_count`. 

2. These two are _not_ equivalent. If you only set `core.procs` to 1, then Manticore will use still use the multiprocessing approach by default. It will only spawn 1 worker process, but it will use `fork` to create it, so only data handled by multiprocessing.SyncManager will be shared between it and the parent process. If you set `core.mprocessing` to single, everything will happen in one process. Ten workers might still be created, but since the calls to `.join` will be synchronous, the first one will do all of the work and the other 9 will exit instantly.
