### ISSUE TITLE
Document properties of Manticore module

### ISSUE THREAD

**Issue by douggard** [trailofbits/manticore#236]
Add documentation for fields like verbosity and workers.

These `@property` fields: https://github.com/trailofbits/manticore/blob/master/manticore/manticore.py#L373

**Comment by mossberg** [comment]
All of these properties, except verbosity, fall under the category of APIs that are incidentally public, but weren't actually discussed, and therefore should be considered even more volatile (may be removed/changed at any point) than the APIs documented the API docs. Since they are especially volatile, I'm hesitant to add them to the official documentation; rather I'd like an issue to be opened for individual APIs so we can have a formal discussion. I'll make an issue to formalize the workers API!

verbosity is documented here: http://manticore.readthedocs.io/en/latest/api.html#manticore.Manticore.verbosity
