### ISSUE TITLE
ARM v7 Support - Invalid Instruction

### ISSUE THREAD

**Issue by mikedefrancis** [trailofbits/manticore#514]
### OS / Environment
Ubuntu 16.04, Raspberry Pi 2

### Manticore version
Latest  as of 2017-09-22

### Python version
2.7

### Dependencies
All installed

### Summary of the problem
Manticore is not decoding ARMv7 instructions correctly.

Additional:
Manticore cannot run a simple "hello world" (or any other) program on the Raspberry Pi 2, because some instructions are unable to be decoded. This is likely an issue with the ARMv7 support within Manticore. 
I am trying to use manticore to create a program that compares the functional equivalence of two .elf binary programs using symbolic execution. I would like to port this program to ARM, but when running manticore (basic install) on my raspberry pi, I get the following error. I am assuming this is a genuine bug since the docs say that manticore supports ARMv7 (e.g., raspberry pi 2).  I am using Ubuntu 16.04.

### Step to reproduce the behavior
Build and run a " hello world" on a raspberry pi and run using manticore

### Expected behavior
ARMv7 instructions need to be decoded correctly in order for manticore to be used for various applications, including efforts being undertaken by large organizations who would like to spread the use of the tool.

### Actual behavior
"Error decoding instruction" thrown 

### Any relevant logs
![test](https://user-images.githubusercontent.com/9902708/31087566-81450060-a76b-11e7-82a4-e8ba84a8ae11.png)

**Comment by yan** [comment]
@mikedefrancis can you provide the binary you were using?

**Comment by catenacyber** [comment]
Here is a binary 
https://github.com/catenacyber/manticore/blob/rasp/tests/binaries/hellorasp

compiled from
```
#include <stdio.h>

int main()
{
    printf("Hello World!\n");
    return 0;
}
```

on 
`Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux`

I do not get the same error.
But I am getting 
```
2018-06-01 11:20:29,456: [36900] m.manticore:INFO: Generated testcase No. 0 - Invalid memory access (mode:r) <0>
```
instead of having "Hello world" printed

Failure happens at
`0x00000000bffc7b70:	ldrb	r2, [r1], #1`
where R1 register is 0, hence the invalid memory access
It is coming from `0x00000000bffbed70:	ldr	r1, [r1, #4]` where R1 value was 0x00000000bffde568

This code is in file `ld-linux-armhf.so.3`

I am trying to debug this.
Have you any advice ?

**Comment by catenacyber** [comment]
I noticed the log info "Unimplemented instruction" for `uqsub8`

Now we go further, but still fail at 
`0x00000000bffb04f0:	ldr	r0, [r4, #0x518]`

**Comment by catenacyber** [comment]
Okay, I finally managed to get my raspberry pi hello world running.

The bug lies in capstone not setting properly the subtracted flag for ldrd operand
I submitted a pull request there :
https://github.com/aquynh/capstone/pull/1163

Ugly workaround would be to check the operation string to look for the lack of minus `ldrd	r2, r3, [r0], #8`

**Comment by mossberg** [comment]
awesome, thank you for debugging this! :D

**Comment by catenacyber** [comment]
You both need #914 and aquynh/capstone#1163 to get it running ;-)

**Comment by mossberg** [comment]
i think we can close this now. the original issue described a error in decoding instructions; this is likely not an actual manticore error, rather it is probably a bug in capstone. we then started discussing and resolved a related but separate issue related to raspi hello world
