### ISSUE TITLE
Provide an API for modifying memory that side-steps permissions

### ISSUE THREAD

**Issue by yan** [trailofbits/manticore#549]
Currently, using `Cpu` and `Memory` methods for writing memory respect permissions set on memory mappings. This is correct for emulation, but can be a hinderance for API usage and custom analysis. Rewriting read-only memory from a hook is currently not possible without using internal methods, but can be useful to do.

This issue proposes adding either another set of methods to the public API to write memory, or an optional keyword parameter (such as `force` or `ignore_permissions`) to existing methods.

**Comment by feliam** [comment]
https://github.com/trailofbits/manticore/blob/master/manticore/platforms/linux.py#L848-L855

**Comment by mossberg** [comment]
I vote for optional kwarg

**Comment by yan** [comment]
Thoughts on naming? I like `ignore_permissions`.

**Comment by mossberg** [comment]
I like `force`. I think it conveys the message, is intuitive, and succinct. We'll document that it ignores permissions in the func docs.

**Comment by yan** [comment]
Agree on `force`

**Comment by mossberg** [comment]
`force` seems to be generally agreed, so I think it's safe to proceed with implementation here. what apis do we need to change? the cpu memory apis are

- write_int
- write_bytes
- write_string
- read_int
- read_bytes
- read_string

all of which are candidates for the optional `force=` parameter. we could add it to all of them, which would be very uniform. alternatively, we could only add it to the `write_` functions, since those were the original use case.

**Comment by yan** [comment]
I vote for including them everywhere as access control is done at a low level (in the `Memory.write()`), so the `force` flag would need to travel from our public APIs all the way down to `write`.

I can submit a PR for this tomorrow afternoon.
