### ISSUE TITLE
Redesign Ethereum API

### ISSUE THREAD

**Issue by offlinemark** [trailofbits/manticore#564]
The manticore ethereum API resides in examples/evm/seth.py, which is not part of the manticore package. This means that it does not get installed from pip, and users of the ethereum API must download the manticore source, which is not ideal, and incongruent with how the rest of the API for linux works.

We need to do API redesign to resolve this.

---

update 2017-12-05, we have trivially moved seth.py into the manticore package, but not done any api redesign

**Comment by mossberg** [comment]
I've been thinking about how to clean up the EVM Api, which looks a little rough now to me. Some things I think we can improve:

### import structure

https://github.com/trailofbits/manticore/blob/d98ef2225137aae3f5a230b42a829d077bae105c/examples/evm/minimal.py#L1-L4

this kind of pattern where we reassign seth looks extremely odd to me

### account creation apis

https://github.com/trailofbits/manticore/blob/d98ef2225137aae3f5a230b42a829d077bae105c/examples/evm/minimal.py#L25-L29

is there any way we can unify these apis into 1 single api?

### static methods

I feel like nearly all of the static methods on ManticoreEVM should actually be functions in a module.

### naming

- iirc `seth` stands for "symbolic ethereum" but I don't think this is very obvious at all.
- `ManticoreEVM`. This class represents the main API object for ethereum api use. Could we call it `Ethereum` or `Blockchain`?
- maybe we can rename the caller and address arguments in `ManticoreEVM.transaction` to `from` and `to`?

### SByte

https://github.com/trailofbits/manticore/blob/d98ef2225137aae3f5a230b42a829d077bae105c/examples/evm/minimal.py#L34

I feel like this doesn't belong inside `ManticoreEVM`, and should belong somewhere else in the package?

### reporting/coverage

https://github.com/trailofbits/manticore/blob/d98ef2225137aae3f5a230b42a829d077bae105c/examples/evm/minimal.py#L41-L48

I don't think manticore itself should be doing raw printing. we should at least move these into helper functions outside the ManticoreEVM class?

**Comment by feliam** [comment]
Good ideas. I'll try to implement some on the ongoing seth-refactor branch.

**Comment by mossberg** [comment]
Some other comments from feliam in chat

```
@mark "ethereum" is used in pyethereum I'm a little afraid to use that name exactly.


[8:08] 
But most of the names I chose are placeholders. (edited)


[8:10] 
Account creation: solidity_create_contract is a high level version of the account_creation. If you do not have solidity you can still use the low level one. We could collapse them but it'll complicate the arguments, I think


[8:12] 
static methods vs. module. I'll have to test how it'll look on the script.


[8:13] 
ManticoreEVM is not a blockchain/ethereum. ManticoreEVM.get_world(id) is a blockchain/ethereum


[8:14] 
Accessing (and feeding symbols) to the list of states transparently is tricky.
```

**Comment by feliam** [comment]
the ongoing refactor and doc was here: https://github.com/trailofbits/manticore/pull/589

**Comment by mossberg** [comment]
from yan:

```
Yan Ivnitskiy [8:22 PM] 
i had no idea seth = sym ethereum


[8:22] 
re: import structure, what about `from manticore.ethereum import Manticore` (so we’ll have two Manticore classes in the lib)
```

**Comment by mossberg** [comment]
> [8:22] 
> re: import structure, what about `from manticore.ethereum import Manticore` (so we’ll have two Manticore classes in the lib)

It think it will be pretty confusing to have two identically named classes that are wildly different.

**Comment by mossberg** [comment]
Some high level thoughts:

- before https://github.com/trailofbits/manticore/pull/521 the Linux/traditional binary analysis API was the primary and only Manticore API
- #521 was merged, theoretically adding an EVM API, but in an imbalanced and kind of half baked way. The EVM API does not reside in the actual manticore package. 
- The EVM API and Linux APIs are quite different, because they are designed for analysis of two very different models of execution (smart contract/blockchain execution environment vs traditional hardware binary execution environment)
- It may be and is probably possible to design one super amazing API that is somehow generic enough to fit both of these execution models. It will probably be a lot of work, and pretty hard to do this.
  - [this](https://github.com/trailofbits/manticore/pull/421#issuecomment-320115817) was my initial attempt at designing such a generic API. it was implemented, but is not a good solution because the EVM API scripts that ultimately exist now cannot be easily ported to it. This is because the concept of a ManticoreEVM API object does not exist in that solution.
- For the moment, let's aim to shoot somewhere in between. We can seek to provide two clean, well designed, and usable APIs that are largely separate, but simply both reside in the manticore package. I believe something like https://github.com/twisted/twisted could be good influence, their API is structured around a large collection of somewhat separate submodules

**Comment by mossberg** [comment]
a perhaps helpful guiding question:

what are the most common use cases for ethereum symbolic execution?

**Comment by mossberg** [comment]
one answer: I have a contract and I want to symex one of its functions and see what paths are reachable. (this is the use case for that one audit we did)

**Comment by feliam** [comment]
`what are the most common use cases for ethereum symbolic execution?`
Other answer.
You have one or more initialization contracts and a trace of concrete transactions that leaves you in an interesting state where you want to try the specific function.

**Comment by feliam** [comment]
`what are the most common use cases for ethereum symbolic execution?`

Yet another answer.
You have one or more solidity contracts and an initial state (storage and balance sheet) where you want to try the specific function. (potentially extracting the state from the actual blockchain?)
