### ISSUE TITLE
symbolic input length

### ISSUE THREAD

**Issue by vanhauser-thc** [trailofbits/manticore#751]
When I just use stdint as input manticore tries different input lengths.

However when I use environment variables or command line options I can only specify specific lengths as symbolic input.

Is there a reason why there is a difference?

I would prefer to say "this program has two command line options, try different lengths for each".

Or am I missing something obvious?

**Comment by mossberg** [comment]
@vanhauser-thc i'll also mention that there's fundamentally no difference in the way manticore provides symbolic stdin, vs symbolic env or arguments -- in all cases, it's a fixed length buffer of symbolic bytes (manticore by default provides 256 symbolic bytes of stdin). so i think manticore should try different input lengths also for symbolic arg and env.

do you have a specific program you can share with us to reproduce this issue?

this is the part of the code where we set up the symbolic inputs:
https://github.com/trailofbits/manticore/blob/master/manticore/manticore.py#L101

**Comment by vanhauser-thc** [comment]
I simple example program would be this:

```
#include <stdio.h>
#include <string.h>

void main(int argc, char *argv[]) {
  char buf[8];

  if (argc > 1)
    strcpy(buf, argv[1]);

  if (strlen(buf) > 12)
    printf("done\n");

  return;
}
```

it triggers a buffer overflow at 8 bytes input and prints a string if the string is longer than 12 bytes.

with manticore there would be now different paths found in the program as I can only specify a fixed length for the input.

**Comment by mossberg** [comment]
Even though the length of the symbolic buffer must be fixed currently, since those symbolic bytes can be NULL, this can simulate multiple string lengths (as long as enough symbolic bytes are given); this is in fact how stdin appears to try different lengths.

I tried running the above code in manticore, but unfortunately, it seems we have some other issues and bugs to deal with there :( Theoretically, if you provided more than 12 symbolic bytes of argv[1] there, Manticore should find both the "done" path, and the other one, since strcpy will cause states forking as it loops through the symbolic argv[1] bytes, and branches if they are NULL or not.

**Comment by mossberg** [comment]
going to close this since it seems resolved
